
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: ${PORT}

#PROD_DB_HOST=containers-us-west-97.railway.app
#PROD_DB_PORT=5925
#PROD_DB_NAME=railway
#PROD_DB_USERNAME=postgres
#PROD_DB_PASSWORD=98K650tkEdETjae07qkU
